FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build

RUN dotnet tool install dotnet-ef --global
ENV PATH="$PATH:/root/.dotnet/tools"

WORKDIR /tmp/source

# Restore projects
COPY ./CarSearch.sln ./CarSearch.sln
COPY ./CarSearch.Worker/CarSearch.Worker.csproj ./CarSearch.Worker/
COPY ./CarSearch.Domain/CarSearch.Domain.csproj ./CarSearch.Domain/
RUN dotnet restore

# Copy source
COPY ./CarSearch.Worker/ ./CarSearch.Worker
COPY ./CarSearch.Domain/ ./CarSearch.Domain